### ISSUE TITLE
Determine what is possible on mobile devices in terms of extensions

### ISSUE THREAD

**Issue by jeffbl** [Shared-Reality-Lab/IMAGE-browser#10]
We were assuming that desktop chrome extensions would work on mobile devices as well. This is actually not clear. We need to understand the limitations of mobile browsers vs. the PC. Eventually, I foresee we're going to have to create some kind of feature table for what is supported on different platforms/browsers...

**Comment by jeffbl** [comment]
@JRegimbal is this truly new news re: firefox on android supporting a wide variety of extensions?
https://www.androidpolice.com/firefox-beta-107-android-install-any-browser-add-on/

**Comment by JRegimbal** [comment]
@jeffbl it's a step in the right direction allowing for extensions to be installed without having to load it in developer mode, but I don't think it adds additional support for extension APIs. It's worth keeping an eye on.

**Comment by 21satvik** [comment]
Hello @jeffbl,

I was testing our first approach to phone client as discussed in the meeting, which is to try something which works with the browser extension. My initial approach was to port the existing chrome extension to a safari browser extension.
Here are the few outcomes I received which may not be favorable to end result but are something to work with:

- Managed to convert web extension for safari from chrome extension
- Web extension runs successfully on Mac and iPhone Safari
- Desktop safari does not produce any output when a graphic Interpretation request is sent
- IOS safari does not show dialogue to send graphic interpretation requests

Looking at the warnings that the Xcode command gave me while porting the extension from chrome to safari, it is clear that the extension is not supported yet by safari. I'll include the warning below:

```
App Name: IMAGE Extension
App Bundle Identifier: ca.mcgill.a11y.image.IMAGE-Extension
Platform: All
Language: Swift
Warning: The following keys in your manifest.json are not supported by your current version of Safari. If these are critical to your extension, you should review your code to see if you need to make changes to support Safari:
	css
	contextMenus
	storage
	downloads
	scripting
	<all_urls>
	default_locale
	open_in_tab
	differential_fingerprint
	version
	name
	type
	default_popup
	resources
	js
	default_icon
	service_worker
	browser_style
	page
	extension_pages
	manifest_version
	icons
	description
```
More on this can be found on [Assessing your Safari web extension’s browser compatibility](https://developer.apple.com/documentation/safariservices/safari_web_extensions/assessing_your_safari_web_extension_s_browser_compatibility)

**Comment by 21satvik** [comment]
@jeffbl Upon testing the IMAGE extension on an iPhone for charts and maps, I discovered that the "Interpret this chart/Map with IMAGE" button is appearing. However, I noticed that the button provides different responses depending on whether I click it on charts or maps.

When I click the button on charts, the webpage refreshes, but no output is generated. On the other hand, when I click the button on maps, there is no response at all.

I have also attached a [screenshot](https://user-images.githubusercontent.com/68138315/224227027-d151d1ca-7408-4c52-a443-6a247ee8f44c.png) for your reference.

**Comment by jeffbl** [comment]
Thanks @21satvik! bottom line seems to be that the extension installs, but likely due to all of the unsupported keys you list, it doesn't work in practice. So the next step would be to begin figuring out whether it is going to be simply impossible to cut the existing extension down enough to fit the capabilities of Safari, or if there are clever ways we can reduce or change functionality to make it fit with what is supported.

**Comment by 21satvik** [comment]
@jeffbl @Cybernide, Closing this issue as I successfully determined how to use the IMAGE extension on mobile devices. The method we are going forward with is to build a Safari extension which works on both iOS and macOS. Using Xcode command-line tools I was able to convert the existing Chrome extension to Safari extension.
