### ISSUE TITLE
Get broken haply's repaired by Haply.

### ISSUE THREAD

**Issue by jeffbl** [Shared-Reality-Lab/IMAGE-browser#101]
At least two of our haply's seem to be broken. We should check on the others and get them to Haply for repairs so that we have enough in good working order through the end of the project.

Antoine asked for photos so that they can plan the repairs and estimate time needed.

Assigning to @dreamseed87, but can be reassigned if someone else is taking charge of this.

**Comment by dreamseed87** [comment]
@johnnyvenom got repaired and replacement joint for that.
