### ISSUE TITLE
Create easy way for IMAGE team members to find/install browser extension reflecting main branch

### ISSUE THREAD

**Issue by jeffbl** [Shared-Reality-Lab/IMAGE-browser#107]
Currently, the extension is automatically built on github, but finding those releases will not be easy for people on the team. We'll have an ongoing need to have IMAGE team members test the latest before it is deployed to google for public access. Creating a new formal github "release" for every single build seems like overkill. Do we want to have a way to formally "bless" a development version of the built extension? What is the best way to do that? Process would be something like:

- developers check into main
- extension automatically builds, so developers can test using that artifact
- around weekly, we update a link somewhere to point people to the latest developer version for more internal testing
- At milestone boundaries, @Clarisa1999 pushes the updated extension to google for public release

Alternative would be to have something like a nightly build pointer on the github readme? Open to suggestions here, but right now, the process is not well-defined and very manual.

**Comment by jeffbl** [comment]
If I'm understanding PR #119 correctly, the idea is that we autotag, then people can just choose the latest tag and get the artifact. However, after that PR, it looks like the tagging happened, but there is no more artifact .zip for the actual extension built:
https://github.com/Shared-Reality-Lab/IMAGE-browser/releases/tag/v0.1.1

**Comment by jaydeepsingh25** [comment]
on digging deeper, i actually found a better way of handling this. Anyone who wants the latest extension build on main branch can get it from the following URL:
https://nightly.link/Shared-Reality-Lab/IMAGE-browser/workflows/typescript-check/main/extension.zip
We can provide this link in README file.
@jeffbl  , can we close this issue if this method is acceptable?

**Comment by jeffbl** [comment]
Great find - that sounds good! If it is live now, can you also pin it in #general channel on slack?

**Comment by jaydeepsingh25** [comment]
@jeffbl , can you please update the README with his link?

**Comment by jeffbl** [comment]
Done. I also need to update the installation instructions, but the link is now in the repo README. Again - great find @jaydeepsingh25. Closing.
