### ISSUE TITLE
Settings for whether user has haptic devices connected

### ISSUE THREAD

**Issue by jeffbl** [Shared-Reality-Lab/IMAGE-browser#110]
We currently do not autodetect whether the user has a Haply or Dot device connected. Perhaps we'll be able to do that eventually. For now, we need two checkboxes added to the settings page, one for "Haply" and one for "Dot" (Probably with a "Haptics" header?).

Work item includes:

- [ ] Add checkboxes to settings page (pending wireframe from UI team) Default state: Both OFF.
- [ ] design and implement a flag that is sent with each request that indicates whether the user has each device

**Comment by Cybernide** [comment]
Never mind, I think I have to consult with @dreamseed87 on some particulars, then draft a number of wireframes and hand them off to @Sabrina-Knappe

**Comment by Cybernide** [comment]
Provided some instructions in a series of comments in the wireframes document. Waiting your feedback, @Sabrina-Knappe

**Comment by Sabrina-Knappe** [comment]
Changes are now reflected in the wireframes:
https://xd.adobe.com/spec/205d4652-e2ff-4aeb-7151-cdbffd27eebd-566c/

**Comment by Sabrina-Knappe** [comment]
Changes have been updated. Assigning this issue to Clarisa for implementation.
The link remains the same : https://xd.adobe.com/spec/205d4652-e2ff-4aeb-7151-cdbffd27eebd-566c/

**Comment by jeffbl** [comment]
Just talked to @Clarisa1999 with @Cybernide. For restricted beta, these will not be present, and the UI will be removed (or "(not yet implemented)" will be added to the text if hiding these controls is difficult) for restricted beta, then implemented fully for open beta. Leaving in "restricted beta" column until the controls are removed or text is changed.

**Comment by jeffbl** [comment]
Note full wireframe in #136
