### ISSUE TITLE
Revisit how the icon appears in the titlebar (it is very tiny and inscrutable:

### ISSUE THREAD

**Issue by Cybernide** [Shared-Reality-Lab/IMAGE-browser#123]
See #74 - might just need to re-crop the icon. I take it that this is fairly straightforward?

**Comment by Sabrina-Knappe** [comment]
I can crop the icon to make it thicker... I made it quite small because the docs told us to make a lot of margin. I will reduce the margin and we can try it again...

**Comment by Sabrina-Knappe** [comment]
So this is without the bumper area around the icon, as well as a re-done crop. I can redo it if we're still unhappy with it, but I think this version is already an improvement over the current icon.
![Asset 16](https://user-images.githubusercontent.com/56092221/153938060-cb331605-82c8-4d24-b400-ddd5cea8df83.png)
s
