### ISSUE TITLE
Undefined key for map requests

### ISSUE THREAD

**Issue by JRegimbal** [Shared-Reality-Lab/IMAGE-browser#124]
The key `url` is used despite the defined key being `URL`. See Shared-Reality-Lab/IMAGE-server#285 for more information about this.

https://github.com/Shared-Reality-Lab/IMAGE-browser/blob/9f41c5e6421c4df0f34e62c4cbd592aa0814e08a/src/background.ts#L73

**Comment by BenMacnaughton** [comment]
Sorry about this. I now see why it managed to get past our testing ("url" was in our mock requests). I will handle the server and schema portion today and address the browser side after OH tomorrow. Should all be easy fixes.

**Comment by JRegimbal** [comment]
No worries it happens!
