### ISSUE TITLE
Create instructions for participants to go on the download page

### ISSUE THREAD

**Issue by Sabrina-Knappe** [Shared-Reality-Lab/IMAGE-browser#125]
Users need to be able to make it directly from the download page to the renderings in ten minutes. What instructions can we provide to make it clear to users what to do?

This is complicated by the variety of screen readers which have different ways of opening context menus. To us "right-click" is the instruction, what would it be for various screen readers?

Sub-tasks:

- [x] Identify what how users on different OS/screenreaders can open a context menu
- [x] Write detailed but concise instructions for users describing how to do this
- [x] Upload these instructions as part of the Chrome Store download page
- [x] Upload these instructions somewhere on the website

Suggest moving out #134 because that would require that I know how to edit the functionality there, and it doesn't look like we have the time to do it.

**Comment by Sabrina-Knappe** [comment]
@jeffbl Feel free to place in whichever milestone is most important

**Comment by jeffbl** [comment]
Putting in restricted beta milestone on the assumption this is something we want to test before we go to open beta (where there will be zero live assistance for people trying it). If we have to caveat to only a subset of OS/screenreader combos, no problem with that, and can expand later.

**Comment by jeffbl** [comment]
Also, ten minutes sounds long to me, but I'm open to debate... My fear is that if it takes that long, many might give up?

**Comment by Sabrina-Knappe** [comment]
I think you're right, maybe amend it to under five minutes?

**Comment by jeffbl** [comment]
I'd time it for someone who knows how to do it already and is an expert, then multiply that by some factor? I wouldn't want to really underestimate when setting a target since things can be quick in one's head, but slower when you actually have to do it. :)

**Comment by Sabrina-Knappe** [comment]
Maybe @Cyan Kuo, ***@***.***> can time it with one of our participants to get a useful metric?

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by Cybernide** [comment]
Hmm. We can probably get Mike to run through it.

**Comment by Cybernide** [comment]
The instruction on opening context menus isn't going to be straightforward. Basic internet research yields the following little nuggets:
- navigating is done using the tab keys, this is a web standard and therefore probably OS-independent
- - suggestion: we use tab as verb in lieu of "select" i.e. "tab to a graphic"
- opening a context menu *is very* OS-specific:
- - On Windows, we know this as right-clicking
- - The Windows keyboard command is Shift-F10
- - on Mac, it's Control-clicking
- - the keyboard command if MouseKeys is enabled is Control-NumPad 5
- - the keyboard command if VoiceOver is enabled is Control-Option-Shift-M
- - - Instruction: "If you're on Windows, open a context menu by either right-clicking, or by pressing Shift-F10. If you're on a Macintosh computer, open a context menu by control-clicking, or if MouseKeys is enabled, Control-Num Pad 5, or if you're using Voiceover, control-option-shift M" <-- this is uber verbose, but might be necessary.

**Comment by Cybernide** [comment]
After discussion, maybe best to teach by analogy, i.e. "Use the tab key to get to the graphic. Similarly to how you would open a context menu to open a link to bookmark it, open a context menu on the graphic."

**Comment by Cybernide** [comment]
Instructions on the website and on the Chrome page have been drafted and are waiting for upload/merge. How does one do this for the icon? I'm investigating this.

**Comment by jeffbl** [comment]
If you're asking how to get revised assets up to the actual chrome store, you need to point @Clarisa1999 to everything, and she can make sure it is built into the release.

**Comment by Cybernide** [comment]
Instructions uploaded
