### ISSUE TITLE
Write new descriptions for renderings

### ISSUE THREAD

**Issue by Cybernide** [Shared-Reality-Lab/IMAGE-browser#126]
Current rendering descriptions:
Rendering 1: A description of the image and its objects
Rendering 2: An audio description of elements in the image with non-speech effects

These are verbose and obtuse. Needs re-writing. @jeffbl to triage.

**Comment by Cybernide** [comment]
The ones in use seem to be:
object-tts: A description of the image and its objects.
segment-handler: "A sonification of segments detected in the image.", "Navigable sonifications of segments detected in the image."
generic-tts-handler: "An audio description of elements in the image with non-speech effects."
hello-tts"An audio description of the elements in the image."

**Comment by Cybernide** [comment]
Instead of referring to them as "Renderings", try "Interpretations"

**Comment by Cybernide** [comment]
As per discussion
Interpretation: Things and People (Object detection)
Interpretation: Outlines of regions (Semantic segmentation)
Interpretation: Regions, things and people, text only (all models, TTS)

**Comment by Cybernide** [comment]
Note: do not use stuff in parentheses, it's just to let us know which rendering its referring to

**Comment by Cybernide** [comment]
@JRegimbal How is it going on this front?

**Comment by JRegimbal** [comment]
These names are incorporated in the new handler which will deprecate the separate object detection and semantic segmentation ones. Once that's in, so will the new descriptions. If you want, the names can be changed in the existing ones now.

**Comment by Cybernide** [comment]
Thank you. Now passing this issue to @jaydeepsingh25  or @Clarisa1999 could you change "Rendering" to "Interpretation" on the popup window?
