### ISSUE TITLE
create video describing IMAGE overall for Chrome Web Store (and website)

### ISSUE THREAD

**Issue by Cybernide** [Shared-Reality-Lab/IMAGE-browser#127]
As the description says. @jeffbl for triage

**Comment by jeffbl** [comment]
@Cybernide I reworked the title - did I capture your intent?

If so, I'm fine with waiting until CSUN milestone for this, since it would be great to have at launch

**Comment by jeffbl** [comment]
Created new project board column for right before CSUN, for items like this, and any fixes after feature freeze.

**Comment by jeffbl** [comment]
@Cybernide At least one of the upcoming conferences requests a video. I think it is optional, but it could potentially be used there as well.

**Comment by Cybernide** [comment]
Yeah it definitely needs to be a thing in case we do more outreach and/or promotion and say, the server is down

**Comment by Cybernide** [comment]
It's in progress, but slow going - recommend moving out

**Comment by jeffbl** [comment]
No pressing need known now that Jun1 talk is over. Moving forward one sprint.

**Comment by Cybernide** [comment]
https://www.youtube.com/watch?v=D5bmL36027s

**Comment by Cybernide** [comment]
I've added it to the Chrome extension store

**Comment by jeffbl** [comment]
Great to have a video overview of the project!

Comments for future versions:
- "which does not rely on textual information" seems like odd phrasing. Not sure people will get what that means.
- for maps, it isn't that information is not commonly provided about surrounding POIs (they often are visually), but that maps typically have NO available non-visual rendering.
- State where the metro map is from (Toronto)

Other items to potentially revise:
- Add the project link to the youtube description, so people can more easily find out more?
- Clicking the existing "shared reality lab" link goes to a page that says there are no videos?

**Comment by Cybernide** [comment]
I've copied this text into a new issue - closing
