### ISSUE TITLE
Update screenshots of extension on the Chrome store page

### ISSUE THREAD

**Issue by Cybernide** [Shared-Reality-Lab/IMAGE-browser#129]
In light of the extensive upcoming UI changes, decided it was prudent to make this its own issue. @jeffbl assigning you for triage; strongly suggest moving this out of the restricted beta, as I expect many of these changes won't take place till open beta is on the horizon.

- [x] Better screenshots that are more representative and better resolution
- [ ] #166
- [ ] #167

**Comment by jeffbl** [comment]
Agree. Triaged to open beta. Please link to the work item where these came from so that they are connected.

**Comment by Cybernide** [comment]
Done
