### ISSUE TITLE
Test & Submit updated chrome extension to web store for restricted beta

### ISSUE THREAD

**Issue by jeffbl** [Shared-Reality-Lab/IMAGE-browser#130]
There are many revisions to the browser extension. Restricted beta participants will not be able to use it until a new version is deployed to the web store.

When all extension changes are done in the Restricted Beta project board column, this work item is to bundle it up and do the actual submission to the web store. @Cybernide once you approve everything and test the extension with all changes, please assign to @Clarisa1999 to do the actual submission.

**Comment by Cybernide** [comment]
Completed on Friday. Closing @jeffbl
