### ISSUE TITLE
Implement a warning in the Settings page to indicate that no renderings will be returned when audio and text checkboxes are unchecked

### ISSUE THREAD

**Issue by Cybernide** [Shared-Reality-Lab/IMAGE-browser#131]
![image](https://user-images.githubusercontent.com/7490996/150859283-68e69100-57bd-41ab-ae7c-3429f8cb9ec0.png)

There needs to be a message indicating that unchecking both of these checkboxes will result in no renderings being returned. Suggest having an invisible label with a message "No interpretations will appear when both Audio and Text are unchecked!". A listener waits until both boxes are unchecked, When the boxes are unchecked, the label becomes visible.

Assigning to @Sabrina-Knappe for wireframing. Please then assign to @Clarisa1999 for implementation.

**Comment by Sabrina-Knappe** [comment]
Wireframe updated: https://xd.adobe.com/spec/205d4652-e2ff-4aeb-7151-cdbffd27eebd-566c/

**Comment by jeffbl** [comment]
@Sabrina-Knappe Did you mean to assign this to Clarisa for implementation? I note that you inserted red text if both checkboxes are unchecked. Do we know whether that will work reasonably well with a screenreader?

**Comment by Sabrina-Knappe** [comment]
Clarisa implemented a popup warning instead, I am going to quickly test how this works with the screenreaders, and we will either confirm that this is a good way to do it or do the red text instead.

We will be providing her with alternate text for the popup to make the behaviour clearer.
