### ISSUE TITLE
Update error messages for beta

### ISSUE THREAD

**Issue by Cybernide** [Shared-Reality-Lab/IMAGE-browser#132]
This message says that our extension is pre-release: "IMAGE is unable to render this graphic. Please note that IMAGE is still in pre-release development, so only works on a limited set of graphics. For working examples, please see https://image.a11y.mcgill.ca."

Suggest change to:

"IMAGE is unable to render this graphic. If you would like to let us know about this, please send a link to this graphic via email: image@cim.mcgill.ca. Please ensure that the graphic you are sending contains no personal information."

**Comment by jeffbl** [comment]
Do we also want to request a description of what they expected? Otherwise we might just get the graphic link, and be unable to determine the actual issue in some cases. (Of course, they can skip this anyway, but wouldn't hurt to ask?)

**Comment by Cybernide** [comment]
OK, what about "IMAGE is unable to render this graphic. If you would like to let us know about this, please send a link to this graphic and a short description of the problem via email: image@cim.mcgill.ca. Please ensure that the graphic you are sending contains no personal information."

**Comment by Cybernide** [comment]
Other error messages point to our old email address: we should change these to image@cim.mcgill.ca.
