### ISSUE TITLE
UI for user information

### ISSUE THREAD

**Issue by jeffbl** [Shared-Reality-Lab/IMAGE-browser#14]
In the browser extension, we'll need to let the user specify what equipment they have, etc, in order to populate the JSON that goes up to the server:

https://bach.cim.mcgill.ca/atp/testpages/tp01/query.json

Also, we need to either have sane defaults, or maybe we can detect whether some of these exist automatically?
Is there a way to guide the user through setting this up after the extension is installed?

Assigning to @Sabrina-Knappe to think about the user interaction side, but @JRegimbal is the extension expert...

**Comment by Cybernide** [comment]
@jeffbl This is now, in actuality a number of different issues and is no longer needed

**Comment by jeffbl** [comment]
Please make sure that in addition to the specific work items for individual settings, that the overall issue of how to guide the user to them if necessary (e.g., autobringup on install) is logged somewhere.

For future, best practice is to list the items that are replacing the item when closing, so that there is an automatic reference back to this issue.

**Comment by Sabrina-Knappe** [comment]
Great, will do.
