### ISSUE TITLE
Put extension web store text into repo so it is versioned and easily findable

### ISSUE THREAD

**Issue by jeffbl** [Shared-Reality-Lab/IMAGE-browser#148]
Right now, the text for the web store entry is all over in documents. Good to get this versioned. Probably a subdir in browser repo, and we'll have to probably add multiple files for different stored, e.g., #83.

**Comment by Cybernide** [comment]
See the commit above - is this sufficient?

**Comment by jeffbl** [comment]
Sure, but in future, there should only be the latest text, otherwise it gets confusing. Since it is versioned, we don't have to keep all the versions visible by extending the file - we can just overwrite, and take the commits with the version so they are easy to find in future if necessary.

**Comment by Cybernide** [comment]
It's the first commit - wanted the older version there for posterity. Can change when we re-release Beta 2

**Comment by jeffbl** [comment]
Hang on, I see this is in a single file in the root of the repo called VERSION. I don't think that will be obvious, and will get confusing when we have different text for different stores? Why not put it in a subdir as originally proposed, something like:

release_resources
       google
            description.txt
            screenshot1.jpg
            screenshot2.jpg
       firefox.txt
             description.txt
             screenshot1.jpg
             screenshot2.jpg

On the assumption we will need (for example) different screenshots for each store?

And when making description.txt, the idea is to put in just the 0.1.0 version, check in, then put in 0.2.0, so that we only ever see the latest, and it is clear what we need to edit? Open to alternatives, but I'm not sure how we'll use the single file I currently see in the branch.

**Comment by Cybernide** [comment]
Fixed. Waiting on UI changes for the screenshots.

**Comment by Cybernide** [comment]
Done
