### ISSUE TITLE
Rendering plays overlapping

### ISSUE THREAD

**Issue by Sabrina-Knappe** [Shared-Reality-Lab/IMAGE-browser#151]
This issue was discovered on mac using VoiceOver, I have not attempted to recreate it with Windows/NVDA yet.

TL;DR
If I press enter on a rendering multiple times in a row, the rendering will just play multiple times, overlapping. We should probably fix this so that pressing enter when it's already playing does nothing.

@Cybernide I've assigned Jaydeep and Clarisa since I'm not sure which one of them is best equipped to tackle this.
@jeffbl so that you see this.

**Comment by jeffbl** [comment]
This happens in Brave on linux with no screen reader running as well

**Comment by JRegimbal** [comment]
If this is just for the segment audio renderer, this will be fixed by #155 since we switch underlying functionality to Plyr.

**Comment by jeffbl** [comment]
Not sure if control redesign will make this a non-issue?
