### ISSUE TITLE
User-facing interface to store logs when filing a bug

### ISSUE THREAD

**Issue by JRegimbal** [Shared-Reality-Lab/IMAGE-browser#154]
For Shared-Reality-Lab/IMAGE-server#314, there needs to be a user-facing functionality to save these logs. Technically this means that when the user reaches a screen to submit a bug for a specific request-response pair the extension must have:

1. The request uuid
2. The [object-hash](https://www.npmjs.com/package/object-hash) of the request

When the user authorizes the logs to be saved, a GET request should be sent to `/authenticate/uuid/hash` where uuid is the actual uuid and hash is the actual object has. This endpoint will return 200 on success, 401 on a mismatched uuid or hash (including on when a request has already been cleaned up after the hour), or 400 if the UUID is not a valid v4 UUID. The browser extension should gracefully handle all these cases with the knowledge that a 400 response should never happen in the real world.

It must be made clear that by sending this request, the user is authorizing us to 1) save the request and response data for as long as we need it for support purposes and 2) examine the actual request and response data.

Assigning to @Cybernide for actual user-facing requirements and any integration into a feedback form if applicable.

EDIT: this endpoint is assumed to be at whatever baseurl is in use. So by default, `https://image.a11y.mcgill.ca/authenticate/uuid/hash`.

EDIT 2: a 503 status will be returned if logging is off on the server, but the feature exists. If the feature doesn't exist on the server, this will result in a 404 error.

**Comment by Cybernide** [comment]
The link in the pop-up should read like this: 
"How did you like these interpretations? Give us feedback or report issues using this form here [link]. [Bold face and/or alert text] Make sure the graphic does not contain any personal information. "

Form gets populated with UUID if it is available, if not, a dummy UUID? I feel like we should still get the feedback even if we cannot retrieve the other data.

After they fill in the form and click "Submit" these two alerts/message boxes/ whatever pop up
"Please review your feedback before continuing to ensure that you are not sending us any private or identifying information [information from fields]." 
[OK] [Go back; I need to change something]
"You are about to submit a report to us about this graphic [either have the graphic there or a link to it]. In doing so, this graphic and your feedback will be kept by us for as long as needed for support purposes. Do you agree to this?"
[Yes; send report and graphic] [No; send report only] [No; do not send report or graphic]

**Comment by jeffbl** [comment]
Why the two separate popups? Why not just one? Also, I'm pretty sure this question needs to be asked before the form is populated and popped up (unless Juliette/Jaydeep said otherwise?). So I think flow is:

User clicks link in rendering window
Popup says (I'm sure needs tweaking...):

Thank you for submitting feedback! Normally, we do not keep or look at the content of your request, such as the graphic, URL, or your settings. However, it is very helpful to us if you allow us to save and access this information to better understand the issues you are describing. If you allow this, we will only save and look at the information from this one request. If you do not want to allow us to access this information, the request will be deleted like normal from our server, and you will still be able to fill out the feedback form.

[Allow request to be saved and looked at, including graphic] [Just fill out the form] [Cancel]

**Comment by Cybernide** [comment]
Popup 1 is asking the user to review, popup 2 is a confirmation - this appears to be in line with how consent is generally obtained when there's the potential for sensitive information?

I thought that doing it this way required a lot more tweaking? I might be misunderstanding things. OK CHange text to:

_Normally, we do not keep or view information such as the graphic, URL, or your settings. However, providing this information to us can potentially improve the quality of your experience in the future. If you agree, we will save and look at the information from this **one request.** If you do not want to allow us to access this information, the request will be deleted like normal from our server, and you will still be able to fill out the feedback form._

[Allow request to be saved and looked at, including graphic] [Just fill out the form] [Cancel]

**Comment by Cybernide** [comment]
I've got the form and I'm playing around with passing dummy UUIDs to it

**Comment by Cybernide** [comment]
Just emailed the two of you with the form
