### ISSUE TITLE
Progress indicator is quiet compared to the renderings and screen readers

### ISSUE THREAD

**Issue by Cybernide** [Shared-Reality-Lab/IMAGE-browser#194]
@JRegimbal you said you're just going to toss it into Audacity and adjust gain? If it's that simple, go for it, but also don't be afraid to assign someone else.

**Comment by jeffbl** [comment]
@JRegimbal this is merged and should be closed, yes?

**Comment by JRegimbal** [comment]
Only the server-side one was. Merging here.
