### ISSUE TITLE
Renderings popup window: feedback text updates

### ISSUE THREAD

**Issue by jeffbl** [Shared-Reality-Lab/IMAGE-browser#198]
Suggest that current text at bottom of renderings popup window that is currently:

> How did you like these interpretations? Give us feedback or report issues by emailing image@cim.mcgill.ca. Feel free to send us a link to the graphic you were using , but make sure you do not send any personal information.
>
> Alternatively, you can use our feedback form.

be changed to:

> How did you like these interpretations? We love getting feedback and bug reports using our feedback form. For anything else, you can also email us at image@cim.mcgill.ca. In either case, please make sure you do not send any personal information.

For two reasons:
1. I think we want to prioritize the feedback form, and encourage people to use that if at all possible. The email is really a fallback.
2. I think that is a bit more light/friendly, and a bit more concise

**Comment by jeffbl** [comment]
Assigned to @Cybernide for vetting before going to @JRegimbal for implementation.

**Comment by Cybernide** [comment]
Yeah, works for me @jeffbl  - let's get this in
