### ISSUE TITLE
Error for no renderings available only has mail link, not feedback form

### ISSUE THREAD

**Issue by jeffbl** [Shared-Reality-Lab/IMAGE-browser#204]
If you have a photo that doesn't return any renderings, it pops up a window that just says something like, "IMAGE can't handle this, please email us to let us know". Since a valid request was made, this should use the [same path as the renderings window](https://github.com/Shared-Reality-Lab/audio-haptic-graphics-UX/issues/26), and allow the user to mark the request as OK for us to look at, and fill out the feedback form to let us know any other detail.

**Comment by jeffbl** [comment]
@Cybernide too late for CSUN unless you think absolutely crucial, unfortunately, but I'd argue this should go in shortly after.

**Comment by jeffbl** [comment]
@hongyec Do you need any further information on this in order to complete it this sprint?

**Comment by hongyec** [comment]
Hi @jeffbl, just back from vocation. Will take a further look at it today!

**Comment by jeffbl** [comment]
Yes, so that the user has the option of pointing us to the graphic that provided the menu item/button, but did not actually return any rendering. The idea is that they might have expected it to work, and maybe it *should* work, but there is some glitch in how we're handling things. UI-wise, it should be as close as possible (identical?) to the case where a rendering is actually returned. If any questions on the UI portion, please ping @Cybernide.
