### ISSUE TITLE
"IMAGE results arrived" progress indicator is apparently not true

### ISSUE THREAD

**Issue by jeffbl** [Shared-Reality-Lab/IMAGE-browser#205]
At CSUN, there seemed to be big problems on their network, especially with maps. After querying, the progress system would eventually say "IMAGE results arrived". However, for maps (e.g. on the tutorial page) the actual rendering window would not show up for something like 40 seconds. This was reduced by [switching to flac](https://github.com/Shared-Reality-Lab/IMAGE-server/pull/401) to reduce the amount of data being downloaded, but "IMAGE results arrived" is misleading if there can be a significant gap before the window appears. Progress indications should reflect actual state, so the "done" indication should come only when the renderings window is actually appearing.

**Comment by jeffbl** [comment]
@hongyec If this was resolved by #206, please close. If not, please comment with what remains to be done.

**Comment by hongyec** [comment]
Hi @jeffbl , I think it has been resolved. I will close it now!
