### ISSUE TITLE
Regression: Local Graphics Not Working

### ISSUE THREAD

**Issue by JRegimbal** [Shared-Reality-Lab/IMAGE-browser#213]
Support for local graphics was added in #36, but no longer works in 2b4aa8f1 (tag 0.1.42).

**Comment by jeffbl** [comment]
@JRegimbal I assume this is most likely on the browser side, so should be assigned to Jaydeep?

**Comment by JRegimbal** [comment]
It seems to be on the browser side from my (brief) look.
