### ISSUE TITLE
Long delay before popup when getting IMAGE rendering

### ISSUE THREAD

**Issue by jeffbl** [Shared-Reality-Lab/IMAGE-browser#236]
Brave on Linux, but Juliette is seeing in Chromium on Linux as well.

Installed latest extension build (https://github.com/Shared-Reality-Lab/IMAGE-browser/actions/runs/2586343477)
Options -> run against unicorn
Enabled Developer mode (but Juliette did not)
Right click and "get IMAGE rendering" on photo from IMAGE homepage
EXPECT: progress popup appears right away
ACTUAL: Up to 5s delay before progress popup appears

Sometimes is is only around 1s, but sometimes it is quite long
Delay seems to be in the extension itself since:
1. Monitoring log output on Unicorn, nothing appears to hit the server until the dialog actually apears (after sometimes considerable delay)
2. Juliette's bash scripts exhibit no delay when making server requests.

Nothing weird on Unicorn - more than half of system RAM available, no appreciable system load. Freshly rebooted this morning.

**Comment by jeffbl** [comment]
For Juliette and me, both charts and maps via the button are both instantaneous, so this appears to be on photos only.

**Comment by JRegimbal** [comment]
Compression is running on all images...
