### ISSUE TITLE
Try Apple's Chrome extension conversion tool to enable extension on Safari/iOS

### ISSUE THREAD

**Issue by jeffbl** [Shared-Reality-Lab/IMAGE-browser#243]
Apple has a [tool for converting a Chrome extension to work on Safari/iOS.](https://developer.apple.com/documentation/safariservices/safari_web_extensions/converting_a_web_extension_for_safari) It is not clear how well this works, or if our extension requires capabilities that are not supported.

Note that the [current extension has to be refactored anyway](https://github.com/Shared-Reality-Lab/IMAGE-browser/issues/199), but hopefully we can get a first approximation of any potential issues with conversion to Apple platform by just trying to convert the existing extension...

**Comment by rohanakut** [comment]
@jeffbl I tried to convert the extension to safari. I had used the latest nightly build(as of Aug 7) for the same. The following were my observations:
1. I did not face any issues in converting the chrome extension to safari. I followed their [documentation](https://developer.apple.com/documentation/safariservices/safari_web_extensions/converting_a_web_extension_for_safari) and did not get any errors during the conversion
2. On testing the extension on safari, I noticed that the extension was sending a request to the server and getting a response. **However, I did not see a response pop-up which displayed the rendering.** 
3. Apart from that the extension was very similar(from UI perspective) to its chrome counterpart. I have attached a few screenshots of the UI to show the similarity.

<img width="1440" alt="Screen Shot 2022-08-07 at 3 52 27 PM" src="https://user-images.githubusercontent.com/27781159/183308803-99e19a69-a088-405d-a3fe-e6fc0b6c29aa.png">
<img width="1440" alt="Screen Shot 2022-08-07 at 3 52 43 PM" src="https://user-images.githubusercontent.com/27781159/183308804-cde02003-55bd-447b-9720-28a32c5ff20f.png">

**Comment by jeffbl** [comment]
@rohanakut Thanks - that is awesome that it builds and runs at all! As discussed at tech-arch, if possible to also try the tool to create an iOS version, that is even more useful, since the major gain would be to get IMAGE working on mobile devices.

**Comment by rohanakut** [comment]
@jeffbl I ran the extension on iOS. The extension builds successfully. However, on running it on an emulator I received the following error
<img width="373" alt="Screen Shot 2022-08-21 at 6 39 42 PM" src="https://user-images.githubusercontent.com/27781159/185813842-d7b8461f-572c-4d6f-b82d-bdb169f43316.png">


I believe this error occurs because the extension takes up too [much memory or is not optimized ](https://developer.apple.com/documentation/safariservices/safari_web_extensions/optimizing_your_web_extension_for_safari)

I was not able to proceed further as the extension did not load up on the emulator

**Comment by rohanakut** [comment]
@jeffbl can this be closed?

**Comment by 21satvik** [comment]
@jeffbl @Cybernide, Closing this issue. I am able to convert Chrome extension to Safari extension using Xcode command-line tools. More on this can be found [here.](https://developer.apple.com/documentation/safariservices/safari_web_extensions/converting_a_web_extension_for_safari)

**Comment by 21satvik** [comment]
@jeffbl @Cybernide, Closing this issue. I am able to convert Chrome extension to Safari extension using Xcode command-line tools. More on this can be found [here.](https://developer.apple.com/documentation/safariservices/safari_web_extensions/converting_a_web_extension_for_safari)
