### ISSUE TITLE
Investigate possible shortcuts/hotkeys for opening the image extension on a graphic

### ISSUE THREAD

**Issue by Sabrina-Knappe** [Shared-Reality-Lab/IMAGE-browser#263]

**Comment by Cybernide** [comment]
So current behaviour on Context menus:
Bringing up a context menu in Windows: Shift-F10
Bringing up a context menu with Voiceover on Mac (default): Ctrl-Option-Shift-M

**Comment by Cybernide** [comment]
Also moving to backlog

**Comment by Cybernide** [comment]
That's a list of current behaviour. Back to you, @Sabrina-Knappe

**Comment by Cybernide** [comment]
I've documented the behaviour in what is currently the UX repo wiki. Closing @jeffbl
