### ISSUE TITLE
Verify object detection SVG overlay is drawn correctly

### ISSUE THREAD

**Issue by jeffbl** [Shared-Reality-Lab/IMAGE-browser#280]
Brave on Linux
Currently nightly build, debug mode on

Testing on the [laptop/coffee cup/phone photo on the IMAGE homepage](https://image.a11y.mcgill.ca/). Object detection rectangles all look like they are drawn too high on the image. For example, the bounding box for the "cell phone" looks like it might properly enclose the phone if shifted down quite a bit, but doesn't even include any pixels of the phone. I'm logging in browser repo in case it is being drawn incorrectly, but this could also be due to the original overlay being miscalculated? (Or is OD really returning results that are way off?!?)

![image](https://user-images.githubusercontent.com/2095406/206828379-1f0d3758-746e-4b32-9ed9-10100f2300c8.png)

**Comment by rohanakut** [comment]
@jeffbl closing this since the PR is merged
