### ISSUE TITLE
Include timestamp of build in extension information

### ISSUE THREAD

**Issue by jeffbl** [Shared-Reality-Lab/IMAGE-browser#286]
Right now, we have a manually incremented version number, but with more focus on test builds going forward, there is a concern about being able to easily identify exactly what build someone is running, so that they can make sure they are up-to-date, and can specify an exact build when logging issues. We had some discussion on this before the break, and my recollection is that we decided a timestamp was the lowest-haning fruit for doing this, but if we need to have a broader discussion about browser extension version numbers and timestamps, happy to do that. Ping to @Cybernide and @JRegimbal since this may impact you as well.

**Comment by JRegimbal** [comment]
Would the build timestamp only appear in the version tag in `manifest.json`, or is this appearing elsewhere too (git, menus, etc.)?

**Comment by Cybernide** [comment]
I think it might be optional in the menus. I feel like I can't speak for the developers on Git.

**Comment by jeffbl** [comment]
git tag sounds like a good idea, since we can reference it directly to a particular version of the code automatically. If easy to do both, even better? The point is that someone should ideally be able to easily divine exactly what version of the code they are running, and how old it is, so that when debugging, we know exactly what was being used, and the user can easily know how up-to-date they are.

**Comment by Cybernide** [comment]
Hey this issue is closed, but thanks! This makes updating the extension maybe only a few seconds faster, but a LOT more convenient for me :)
