### ISSUE TITLE
Image Size to Pass To Server

### ISSUE THREAD

**Issue by JRegimbal** [Shared-Reality-Lab/IMAGE-browser#29]
Currently, the size of the image sent to the server is exactly the size it appears on screen. In other words, a high resolution image that is displayed as a small teaser on the page will be sent to the server at the quality of that small teaser and **not** the high resolution original, even if that is the source.

This is partially a side effect of how we go about actually getting the image binary in the extension (which could possibly be changed) and was justified earlier by me as roughly providing the same image size and level of detail that a sighted person would have access to. Plus, I've seen some cases where *very* large images (think 40 MB or more) are embedded into pages and sending such large payloads if they aren't actually being usefully used can create breaking technical problems (e.g., Shared-Reality-Lab/auditory-haptic-graphics-server#41).

I'm raising this as something we need to consider since this impacts the results of ML preprocessing and thus the renderings we can make, *if any can be made given the results of preprocessing*. For some demo images at the quality they are on the test page, it seems that no objects are being detected and the hello-tts-handler (which is not a production handler by any means) then cannot render anything. This *may* impact other renderings we actually do want to demo though, and a message in the browser saying we can't handle an image could turn some heads.

@jeffbl I'm mentioning you here so you're aware of this and can weigh in.

**Comment by jeffbl** [comment]
@JRegimbal It is passing the actual full image now, so this is no longer an issue.
