### ISSUE TITLE
Weird double map buttons don't bring up any maps

### ISSUE THREAD

**Issue by jeffbl** [Shared-Reality-Lab/IMAGE-browser#308]
Brave on Linux, current (test) version of browser extension.

Go to this webpage:
https://www.hexoskin.com/pages/contact-us

At bottom, there is a map. Below it, I see this:

![image](https://user-images.githubusercontent.com/2095406/231491956-538eebe2-8f4e-4a97-92fd-f220bc7f847d.png)

Note: two buttons, not one
Note: formatting looks like native to the page (this could be good or bad, but was a surprise to me)
Note: neither button triggers IMAGE

Expect: If not in a format we can use, button should not be present
Expect: Unless there are two maps, there should not be two buttons
Expect: Unclear if having the page formatting is a good or bad thing (@Cybernide opinion?)

**Comment by Cybernide** [comment]
I'm leaning towards "no" as I think visual consistency is probably important to those who have enough vision to search the page.
