### ISSUE TITLE
When extension installation completes, pop up browser window with tutorial page

### ISSUE THREAD

**Issue by jeffbl** [Shared-Reality-Lab/IMAGE-browser#309]
#301 is for creating a tutorial page that tells users how to use IMAGE right after they install the extension. The current take is that this will be done with a webpage on the IMAGE website, so that we can modify it as needed without having to push a new extension version. For now, this will be a blank page until @Cybernide has time to design it as part of #301. Work item is to automatically bring up the tutorial webpage when installation of the browser extension finishes.

@Cybernide Please add URL to use for page.

@Cybernide Please specify if it should be a popup window or a new tab within the browser (I don't think we actually discussed that?)

@Cybernide Please vet description and add/change anything else I missed from our discussion, then assign to Jaydeep.

**Comment by Cybernide** [comment]
> @Cybernide Please add URL to use for page.
https://image.a11y.mcgill.ca/pages/quick-help.html

> @Cybernide Please specify if it should be a popup window or a new tab within the browser (I don't think we actually discussed that?)
Pop-up is good

> @Cybernide Please vet description and add/change anything else I missed from our discussion, then assign to Jaydeep.
Wireframe [here](https://github.com/Shared-Reality-Lab/IMAGE-UX/blob/main/ui-wireframes-mockups/UI_FirstRun.json)

[Instructions for loading the wireframe into mydraft.cc](https://github.com/Shared-Reality-Lab/IMAGE-UX/tree/main/ui-wireframes-mockups#readme)

**Comment by Cybernide** [comment]
@jaydeepsingh25 Please let me know if unclear, I am away from the 20th-27th
