### ISSUE TITLE
STORY: As an IMAGE user who is blind, I want to easily access all of IMAGE's functionality, so that I can trigger IMAGE's functionality without having to navigate the standard browser extension UI

### ISSUE THREAD

**Issue by jeffbl** [Shared-Reality-Lab/IMAGE-browser#310]
Cyan has proposed an IMAGE Launchpad that pops up a window that lets the user easily select different IMAGE functionality. Work item is to:

- [ ] Implement hotkey [`ALT + I`] that brings up Launchpad popup window
- [ ] Add button for "IMAGE options" that brings up the existing options panel

Note that new buttons will be added for further functionality in the future.

@Cybernide Please attach wireframe for desired popup window.

**Comment by jeffbl** [comment]
Note additional button to add for using local graphics work item, separately #296

**Comment by Cybernide** [comment]
See wireframe here:
https://mydraft.cc/cgrpdqhterm4uu9brvcg

**Comment by Cybernide** [comment]
*Single* key. Well that's limiting. Thanks for digging up this link, though. I was hoping to avoid Ctrl+I because it's very nearly a convention for word processing applications. I think `Alt+I` would be the lesser of all these evils. Let's go with that.
