### ISSUE TITLE
Fix SVG debug output

### ISSUE THREAD

**Issue by jaydeepsingh25** [Shared-Reality-Lab/IMAGE-browser#313]
The resizing of SVG output has introduced the following issues:

- The SVG output for depth map is distorted, It is not being resized to original graphic size
- The aspect ratio of the graphic is disturbed during resizing. This should remain intact.

**Comment by emmanuelwilson** [comment]
@jaydeepsingh25 Is there something I need to do to have the nightly extension? Or is that the test extension? I don't think I have the right version as I am still seeing the same problems as before and the aspect ratio is still off. I'm excited to see it the result!!

**Comment by jeffbl** [comment]
Nightly extension link is pinned in slack #general.

**Comment by emmanuelwilson** [comment]
@jaydeepsingh25 Can confirm that the nightly build works! Great job!!! Thank you for fixing it!

**Comment by jeffbl** [comment]
Already closed, but @jaydeepsingh25 thanks for doing this - tested with nightly extension, and maintaining aspect ratio makes this much, much better.
