### ISSUE TITLE
User test invisible buttons added to photos

### ISSUE THREAD

**Issue by jeffbl** [Shared-Reality-Lab/IMAGE-browser#331]
@jaydeepsingh25  just did a quick test of the custom build from #311 . I don't see any visual artifacts, but if I tab once after a photo and hit space, it indeed triggers IMAGE, which is very cool. I didn't try with a screen reader to determine if it reads out something when tabbed, so that the user knows they can activate IMAGE. @Cyan the special build in #311 was created for testing. Is there anything else you need? I've created this issue to track testing. If/when we want to move this into main / intro production, please assign a new work item to @jaydeepsingh25, as this issue is just to keep the user testing on the project board.

**Comment by jeffbl** [comment]
@Cybernide logged into Jul31 sprint since current sprint is only one week from over, and I assume this will take some time. However, if any additional implementation is required, need to get that to Jaydeep asap.

**Comment by Cybernide** [comment]
Tested on Windows using:
Edge, Chrome, Opera. Working with JAWS, NVDA, and windows Narrator.

Works beautifully.

To be done:
Testing on Macintosh using Safari and Voiceover

Do I have any other test cases to take care of? Please let me know.

**Comment by Cybernide** [comment]
Closing for now, but I anticipate reopening this issue once 
- we have this version of the extension on Safari and iOS. 
- this version of the extension is tested on participants
@jaydeepsingh25 good job, and @jeffbl let me know if these plans work for you.
