### ISSUE TITLE
Story: As a 2diy integration developer, I want to provide an option to the user to select the version of haply device connected.

### ISSUE THREAD

**Issue by jaydeepsingh25** [Shared-Reality-Lab/IMAGE-browser#336]
As the device integration is completed in the #321 , We now need to modify the options page to allow extension user to select the haply device version connected to the extension. Once this work-item is completed, the extension should work with both the versions of 2diy.

**Comment by jeffbl** [comment]
@jaydeepsingh25 I think this is done? If so, pelase close. Otherwise, please note what still remains to be done.
