### ISSUE TITLE
Translate the Chrome store text and screenies

### ISSUE THREAD

**Issue by Cybernide** [Shared-Reality-Lab/IMAGE-browser#346]
Currently all the text is in English. The Chrome extensions store page needs to be translated to French.

**Comment by Cybernide** [comment]
Could someone please check the French:

> Extension du projet McGill IMAGE. Il s'agit d'une version bêta.
> 
> Rendre les graphiques d'Internet accessibles grâce à l'audio et au toucher !
> 
> Avez-vous déjà eu envie d'entendre une photographie ou un diagramme circulaire, et pas seulement une description de ce qu'ils contiennent ? IMAGE (Internet Multimodal Access to Graphical Exploration) offre aux personnes aveugles ou malvoyantes une expérience nouvelle et utile des graphiques Internet, qui va au-delà de la génération automatique de balises alt.
> 
> Une fois que vous avez ajouté l'extension à votre navigateur, un bouton est ajouté aux graphiques du site web pour activer IMAGE, ou bien vous pouvez utiliser le menu contextuel en cliquant avec le bouton droit de la souris pour activer IMAGE. Le graphique est envoyé à un serveur qui crée un rendu audio personnalisé et, si vous portez un casque, utilise un "son spatialisé" pour que vous entendiez les différentes parties du graphique tout autour de vous, sous forme de sons. En outre, si vous vous rendez sur la page de configuration de l'extension, vous pouvez activer des dispositifs haptiques tels que le Haply et le Dot Pad afin d'explorer les graphiques avec votre sens du toucher.
> 
> Cette version est une version bêta d'IMAGE et ne fonctionne pas correctement sur tous les graphiques. Pour commencer, nous vous recommandons de consulter notre page de tutoriel à l'adresse https://image.a11y.mcgill.ca/pages/tutorial.html.
> 
> IMAGE est réalisé par le Shared Reality Lab (SRL) de l'Université McGill [1], en partenariat stratégique avec Gateway Navigation CCC Ltd [2] et le Conseil canadien des aveugles (CCA) [3]. Le projet est financé par le Programme de technologies d'assistance d'Innovation, Sciences et Développement économique Canada. La motivation de ce projet est d'améliorer l'accès aux graphiques Internet pour les personnes aveugles ou malvoyantes.
> 
> Pour plus d'informations sur la manière dont nous traitons vos données, veuillez consulter :
> https://image.a11y.mcgill.ca/pages/policies.html
> 
> Pour les questions techniques, veuillez contacter image@cim.mcgill.ca.
> Pour toute autre question, veuillez contacter image@gnc3.com.
> 
> À PROPOS DE NOUS
> 
> [1] Le laboratoire de réalité partagée du département de génie électrique et informatique de l'Université McGill travaille avec les technologies audio, vidéo et vidéo.
> d'ingénierie électrique et informatique, travaille sur les technologies audio, vidéo et
> haptiques, en construisant des systèmes qui tirent parti de leurs capacités
> pour faciliter et enrichir l'interaction entre l'homme et l'ordinateur et l'interaction
> l'interaction entre l'homme et l'ordinateur et entre l'homme et l'homme. http://srl.mcgill.ca
> 
> [2] Gateway Navigation CCC Limited est une entreprise sociale unique en son genre.
> qui réunit l'innovation sociale et la durabilité à but lucratif.
> Fondée en 2017 par des individus et des organisations, dont le
> Conseil canadien des aveugles (CCA). Partageant une expérience vécue en matière de
> handicap et une passion pour faire une différence dans nos communautés. Notre
> objectif social et commercial est de créer un monde plus accessible et plus
> accessible et inclusif en appliquant une conception centrée sur l'humain dans l'utilisation de
> réseaux de réalité augmentée (numérique) basés sur l'audio, tout en favorisant la formation et l'emploi des personnes handicapées.
> tout en promouvant la formation et les opportunités d'emploi pour les personnes
> handicapées dans ce secteur technologique en plein essor.
> https://gnc3.com/
> 
> [3] Le Conseil canadien des aveugles (CCA) est la plus grande organisation de consommateurs de personnes aveugles.
> organisation de consommateurs composée de membres, qui regroupe des personnes aveugles, sourdes et aveugles ou partiellement aveugles,
> sourdes-aveugles ou malvoyantes au Canada. https://ccbnational.net/

In Englis

**Comment by rbazin** [comment]
It's pretty good ! @Cybernide 
I made some modifications (in bold) to translate some expressions little more authentically..

"""
French extension IMAGE

Extension du projet McGill IMAGE. Il s'agit d'une version bêta.
Rendre les graphiques d'Internet accessibles grâce à l'audio et au toucher !
Avez-vous déjà eu envie d'entendre une photographie ou un diagramme circulaire, et pas seulement une description de ce qu'ils contiennent ? IMAGE (Internet Multimodal Access to Graphical Exploration) offre aux personnes aveugles ou malvoyantes une expérience nouvelle et utile des graphiques sur Internet, qui va au-delà de la génération automatique de balises alt.
Une fois que vous avez ajouté l'extension à votre navigateur, un bouton est ajouté aux graphiques **des sites internet**. **Pour activer IMAGE, cliquez sur ce bouton, ou utilisez le menu contextuel en cliquant sur le bouton droit de la souris**. Le graphique est envoyé à un serveur qui crée un rendu audio personnalisé et, si vous portez un casque, utilise un "son spatialisé" pour que vous entendiez les différentes parties du graphique tout autour de vous, sous forme de sons. En outre, si vous vous rendez sur la page de configuration de l'extension, vous pouvez activer des dispositifs haptiques tels que le Haply et le Dot Pad afin d'explorer les graphiques avec votre sens du toucher.
Cette version est une version bêta d'IMAGE et ne fonctionne pas correctement sur tous les graphiques. Pour commencer, nous vous recommandons de consulter notre page de tutoriel à l'adresse https://image.a11y.mcgill.ca/pages/tutorial.html.
IMAGE est réalisé par le Shared Reality Lab (SRL) de l'Université McGill [1], en partenariat stratégique avec Gateway Navigation CCC Ltd [2] et le Conseil canadien des aveugles (CCA) [3]. Le projet est financé par le Programme de technologies d'assistance d'Innovation, Sciences et Développement économique Canada. La motivation de ce projet est d'améliorer l'accès aux graphiques sur Internet pour les personnes aveugles ou malvoyantes.
Pour plus d'informations sur la manière dont nous traitons vos données, veuillez consulter : https://image.a11y.mcgill.ca/pages/policies.html
Pour les questions techniques, veuillez contacter [image@cim.mcgill.ca](mailto:image@cim.mcgill.ca). Pour toute autre question, veuillez contacter [image@gnc3.com](mailto:image@gnc3.com).
À PROPOS DE NOUS
[1] Le laboratoire de réalité partagée du département de génie électrique et informatique de l'Université McGill travaille avec les technologies audio, vidéo et vidéo. d'ingénierie électrique et informatique, travaille sur les technologies audio, vidéo et haptiques, en construisant des systèmes qui tirent parti de leurs capacités pour faciliter et enrichir l'interaction entre l'homme et l'ordinateur et l'interaction l'interaction entre l'homme et l'ordinateur et entre l'homme et l'homme. http://srl.mcgill.ca/
[2] Gateway Navigation CCC Limited est une entreprise sociale unique en son genre. qui réunit l'innovation sociale et la durabilité à but lucratif. Fondée en 2017 par des individus et des organisations, dont le Conseil canadien des aveugles (CCA). Partageant une expérience vécue en matière de handicap et une passion pour faire une différence dans nos communautés. Notre objectif social et commercial est de créer un monde **de plus en plus accessible** et inclusif en appliquant une conception centrée sur l'humain dans l'utilisation de réseaux de réalité augmentée (numérique) basés sur l'audio, tout en favorisant la formation et l'emploi des personnes handicapées. **tout en promouvant la formation et les opportunités d'emploi pour les personnes handicapées dans ce secteur technologique en plein essor. [duplicate with previous sentence ?]** https://gnc3.com/
[3] Le Conseil canadien des aveugles (CCA) est la plus grande organisation de consommateurs de personnes aveugles. organisation de consommateurs composée de membres, qui regroupe des personnes aveugles, sourdes et aveugles ou partiellement aveugles, sourdes-aveugles ou malvoyantes au Canada. https://ccbnational.net/
"""

**Comment by JRegimbal** [comment]
Content of [1] includes duplicate text and reads very clearly translated. Some additional suggestions in *italics*.

---

Extension du projet McGill IMAGE. Il s'agit d'une version bêta.
Rendre les graphiques d'Internet accessibles grâce à l'audio et au toucher !
Avez-vous déjà eu envie d'entendre une photographie ou un diagramme circulaire, et pas seulement une description de ce qu'ils contiennent ? IMAGE (Internet Multimodal Access to Graphical Exploration) offre aux personnes aveugles ou malvoyantes une expérience nouvelle et utile des graphiques sur Internet, qui va au-delà de la génération automatique de *texte de remplacement*.
Une fois que vous avez ajouté l'extension à votre navigateur, un bouton est ajouté aux graphiques **des sites internet. Pour activer IMAGE, cliquez sur ce bouton, ou utilisez le menu contextuel en cliquant sur le bouton droit de la souris**. Le graphique est envoyé à un serveur qui crée un rendu audio personnalisé et, si vous portez un casque, utilise un "son spatialisé" pour que vous entendiez les différentes parties du graphique tout autour de vous, sous forme de sons. En outre, si vous vous rendez sur la page de configuration de l'extension, vous pouvez activer des dispositifs haptiques tels que le Haply *2diy* et le Dot Pad afin d'explorer les graphiques avec votre sens du toucher.
Cette version est une version bêta d'IMAGE et ne fonctionne pas correctement sur tous les graphiques. Pour commencer, nous vous recommandons de consulter notre page de tutoriel à l'adresse https://image.a11y.mcgill.ca/pages/tutorial.html.
IMAGE est réalisé par le Shared Reality Lab (SRL) de l'Université McGill [1], en partenariat stratégique avec Gateway Navigation CCC Ltd [2] et le Conseil canadien des aveugles (CCA) [3]. Le projet est financé par le Programme de technologies d'assistance d'Innovation, Sciences et Développement économique Canada. La motivation de ce projet est d'améliorer l'accès aux graphiques sur Internet pour les personnes aveugles ou malvoyantes.
Pour plus d'informations sur la manière dont nous traitons vos données, veuillez consulter : *https://image.a11y.mcgill.ca/fr/pages/policies.html*
Pour les questions techniques, veuillez contacter [image@cim.mcgill.ca](mailto:image@cim.mcgill.ca).  Pour toute autre question, veuillez contacter [image@gnc3.com](mailto:image@gnc3.com).

**Comment by emmanuelwilson** [comment]
Another small edit suggestion, perhaps rather than "casque" you might want to swap it for " écouteur".

**Comment by Cybernide** [comment]
OK I've added this to the draft for the next full release.
