### ISSUE TITLE
Alt-I not documented anywhere?

### ISSUE THREAD

**Issue by jeffbl** [Shared-Reality-Lab/IMAGE-browser#352]
Couldn't remember the Alt-I keyboard shortcut to bring up the IMAGE options panel
Installed browser extension, got popup and went to quickstart.
NOTE: Did not see any mention of this shortcut
EXPECT: Since this is the only way I think we expect someone blind or low vision to be able to access functionality including triggering IMAGE on a local photo, and to get to options, this is crucial, so should be conveyed and reinforced.

**Comment by jeffbl** [comment]
@Cybernide moving to Oct23 sprint, on assumption that this is necessary before user testing of install/use experience? If incorrect, let me know if needs  to move further out, or to backlog?

**Comment by Cybernide** [comment]
Alt+I documented in the longer tutorial. I am also going to update Quick start so that Alt-I is there as well. Closing @jeffbl
