### ISSUE TITLE
Fix inconsistent usage of 'renderings' and 'interpretations' in IMAGE extension windows (for both English and French)

### ISSUE THREAD

**Issue by Cybernide** [Shared-Reality-Lab/IMAGE-browser#361]
See pull request  #356 for more context.

**Comment by Cybernide** [comment]
@jeffbl for triage

**Comment by jeffbl** [comment]
@Cybernide related PR is assigned to you. Is this able to be completed by Dec11 sprint end, or should this move to backlog?

**Comment by jeffbl** [comment]
@Cybernide are you still pending anything from me on this?

**Comment by Cybernide** [comment]
Oops, forgot to reassign this - the French readers/writers need to vet my translations

**Comment by emmanuelwilson** [comment]
> @Cybernide where can we see the content again?

Its the live French version of the Website is it not? 
I have been putting my reviews in this google doc: 
https://docs.google.com/document/d/13L6-eJn0AJyQqRoz3H-d8bM0UWVWg32DsWPDFINfCQ0/edit?usp=sharing

**Comment by emmanuelwilson** [comment]
I just went through the entire french website. There are quite a few corrections to be made and a couple of things that were not updated! You can look at my suggestions in the link above

**Comment by Cybernide** [comment]
Some of the feedback indicates significant re-writes of the French section are necessary.

**Comment by Cybernide** [comment]
@JRegimbal and @emmanuelwilson Think you can take another glance? The changes aren't live, so I'll send you a PDF of the webpages.

**Comment by Cybernide** [comment]
Mentioned in new issue. Closing @jeffbl
