### ISSUE TITLE
STORY: As a 2diy photo experience developer, I want to create sample 2diy texture experiences for pre-selected photos, so that I can discover what makes effective haptic experiences.

### ISSUE THREAD

**Issue by LukeBebee** [Shared-Reality-Lab/IMAGE-browser#362]
Subtasks:
- [x] Meet with @Cybernide (Cyan) to discuss previous usability test findings to inform our samples
- [x] Meet with @rayanisran (Rayan) to go over previous haptic experiences to inform our samples
- [x] Get access to specific haptic feedback experiences mentioned in the Oct 23 sprint meeting (viscosity, plucking, etc.)
- [x] Use tools in the IMAGE repository to segment images for our samples in Processor
- [x] Create 2 samples of haptic mappings to test design decisions such as borders between textures and forcing user motion like flowing down a river. Use the lighthouse image from our first demo as well as the mountain picture provided by Cyan on Slack.

**Comment by LukeBebee** [comment]
We only created one sample this week and we did not fully explore haptic design decisions that can be made. Exploration of design decisions will be more focused in the next sprint.
We have access to the segmentation tools in the IMAGE repo but have not been able to get the output from them yet.
Creating the demo and [making physical adjustments to 2diys](https://github.com/Shared-Reality-Lab/IMAGE-server/issues/785) took longer than expected, which is why we did not fully complete the subtasks.

**Comment by jeffbl** [comment]
Moving to "almost done" since it sounds close to being complete. I'm not sure what you mean by "we have access to the segmentation tools...but have not been able to get the output". Please ping me if need clarity here, because you should be able to just get the preprocessor results from the extension by enabling developer mode. (So I assume this means something else, but I would hate to have you waste time for no reason!)

**Comment by LukeBebee** [comment]
Closing and moving leftover subtasks to new sprint story. 

The segmentation tool we are talking about lets us draw our own segments (image contour exporter in the IMAGE-UX repo). We have already been able to get the preprocessor output, but its not always exactly what we want for pictures (sometimes the segmentation is off or doesn't include segments we want).
