### ISSUE TITLE
Verify browser extension manifest V3 compliance

### ISSUE THREAD

**Issue by jeffbl** [Shared-Reality-Lab/IMAGE-browser#367]
received an email from Google indicating that our account still has Manifest V2 extensions published. We don't have any non-IMAGE extensions to my knowledge, so this implies that we haven't done some step that makes us fully V3 compliant.

> To: 	[sharedrealitylab@gmail.com](mailto:sharedrealitylab@gmail.com)
> You still have one or more published extensions currently running on Manifest Version 2, which has been deprecated. We recently announced the updated phase-out timeline of Manifest V2, and your item(s) will be impacted by these changes.
> More specifically, if you have not migrated to Manifest V3 by June 2024, your Manifest V2 extension may begin to be disabled on Chrome browsers ...

Need to verify both the production and test extensions are fully Manifest V3 compliant. Don't know how that could not be the case given `manifest.json` specifically says V3:

https://github.com/Shared-Reality-Lab/IMAGE-browser/blob/b4789596d5deda026a789eb0b1621ac2f8a43194/src/manifest.json#L2

@Cybernide if you have access to the google account and can see all our extensions listed, is there any further indication of what might not be in compliance? If you could check, then assign to @jaydeepsingh25 with any relevant information, hopefully we find this is just a spurious notification or applies to an old extension or something, but best to be sure so we don't break in June 2024.

**Comment by Cybernide** [comment]
Did some Googling but the only documentation I could find were:
https://developer.chrome.com/docs/webstore/troubleshooting#additional-requirements-for-manifest-v3
https://developer.chrome.com/docs/extensions/develop/migrate/checklist
