### ISSUE TITLE
STORY: As a teacher, I want to be able to install and use the IMAGE extension without worrying about it interfering with my typical web use, so that I can use just one IMAGE tool to generate content and run my classroom rather than a separate tool I need to install and use.

### ISSUE THREAD

**Issue by jeffbl** [Shared-Reality-Lab/IMAGE-browser#384]
The concern is that we have had a large number of web "weirdnesses" with the IMAGE extension installed, including IMAGE triggering when clicking unrelated buttons and UI elements on pages, IMAGE text being inserted into online documents and printouts, etc. We have been fixing these one-by-one, but we need to determine if this is a fight we can win, or if there will always be weirdnesses that will cause users issues even when they aren't using IMAGE, just because they have the extension installed and active.

If we cannot find a solid way to overcome these issues and be confident that users will not have such impacts, we need to consider implementing additional functionality, such as the teacher tools for Monarch content editing, outside of the extension so that teachers' normal web use is not impacted. This would be bad for two reasons: 1. we'd have to implement and maintain two separate tools, document their use, etc. 2. teachers would have to understand when to use the extension vs. this other tool, which is bound to be confusing.

I don't know what the reasonable alternatives are, but continuing to fix bugs one by one may be a fight we need to give up. If so, how do we do content selection going forward?

Note that this story is really about investigation and coming up with a proposal in which we can have confidence, for implementation in a future sprint.

Ping @JRegimbal @Cybernide @VenissaCarolQuadros to weigh in on additional concerns/options.

**Comment by Cybernide** [comment]
Just my pseudo-philosophical ramblings, but I wonder if, given the heterogeneity of web documents and how quickly formats and standards evolve, this is ultimately futile. Having spent a little time with some screenreaders, I've noticed that even the likes of Apple and Freedom Scientific can't always pick up photographs depending on how they're embedded on a webpage. Our team is plucky, but that's a really tall order to find every instance of a graphic without perhaps getting too permissive as to what that even means.

**Comment by jeffbl** [comment]
@Cybernide I'm actually less worried about finding all the graphics due to weird embeddings, and more about all of the ancillary side issues that have cropped up that could cause serious annoyance, including:

- #378 
- #376 
- #377 

@jaydeepsingh25 the key issue here is whether the extension is likely to be unintrusive enough that a teacher will feel confident leaving it installed all the time. If so, we can use it as the central gateway to all things IMAGE, including adding in the teacher UI for managing Monarch experiences. You've been fixing issues including the examples above. The question is whether these are indicative of more deep-seated issues. If so, are they fixable, or is the nature of the web just that we're not going to be able to leave the extension enabled all the time, due to such intrusive weirdnesses.

My opinion is that we should strive *very* hard to include the teaching tools in the extension, since otherwise we'll have another codebase to maintain separately, and I fear that we'll end up repeating a bunch of the code in two places, e.g., for content selection. Plus, the Monarch use cases require content selection, and if that is the core issue causing issues with the extension, I don't see how we'll magically solve that outside of the extension, so we'll just have two content selection tools that are janky in different ways.

**Comment by jeffbl** [comment]
Decision is made to incorporate into browser extension, so can be closed as new items have been logged.
Assigning to @Cybernide for any other items to break out before closing.

**Comment by Cybernide** [comment]
Based on the very early results of UI testing, the number of embeddings can be overwhelming to BLV as well. In case of TL;DR, the proposed solutions for now are to:
1 toggle buttons on and off with a hotkey and/or setting in the options panel.
2 activate IMAGE by directly tabbing onto a photo/map/chart and using a hotkey on the selected item. (If possible, there should be a sound that plays when activation is attempted on an invalid item.)

I suggest we try having both options available for now.

I will investigate hotkey options, but @jaydeepsingh25 should feel free to use something temporary in the meantime for testing out implementation.

---

Thus far, participants are lukewarm about prioritizing discovery with buttons or new interface items at best. The buttons do break up the flow of navigation to them. Their argument is "well of course I know that I have this extension, I don't need a button to tell me that I can use it on things." When we start testing on maps and charts, I'll have a better idea of whether buttons should be scrapped or kept.

**Comment by jeffbl** [comment]
Closing in favor of newly logged issues (@Cybernide I assume #390 is the only one you want to log out of this)
