### ISSUE TITLE
Choose "Activate IMAGE" command key combo

### ISSUE THREAD

**Issue by jeffbl** [Shared-Reality-Lab/IMAGE-browser#389]
After #388 has proven out activating a command key to trigger IMAGE on specific photos/maps/(maybe)charts, we'll need to select a specific key, taking into account OS, screen reader, and browser choices.

**Comment by Cybernide** [comment]
@jaydeepsingh25 is it possible to use a 3-key combination?

**Comment by Cybernide** [comment]
Checked the nightly build and @jaydeepsingh25 I think this works nicely. Can we make a new test extension soon?
