### ISSUE TITLE
Move Monarch Link Polling App to unicorn/pegasus

### ISSUE THREAD

**Issue by jeffbl** [Shared-Reality-Lab/IMAGE-browser#392]
Right now, @VenissaCarolQuadros has the Monarch Link Polling app running on a personal server for testing. This will need to be deployed on unicorn/pegasus as part of our overall stack.

Caveat: Is this mechanism likely to be the one that we use for the duration of this grant? If so, we should go ahead, but I want to make sure there isn't a cleaner publish/subscribe mechanism we should explore that would remove the need for continuous polling. Assuming we go ahead:

- [ ] @JRegimbal I don't think we have anything like this running on our stack so far. It isn't a preprocessor, it isn't a handler. It is more like a service, but one that is used not by handlers, but by clients directly. Do we need some kind of name for this?
- [ ] I assume this will need to be dockerized as a separate container so that it fits into our overall deployment mechanism
- [ ] New traefik endpoint will be needed so clients know where to access this (@JRegimbal). This should be sensitive to the server URL set in the options panel, so that if you're running against unicorn, it is hitting this app running on unicorn rather than pegasus.

FYI ping to @shahdyousefak since this is a new component going in for the server stack.

**Comment by jeffbl** [comment]
Note that the current polling system uses pythonanywhere.com, including to store the JSON of the experiences, which would need to be changed before any user studies. (@VenissaCarolQuadros please correct me if I'm off base here!)

**Comment by VenissaCarolQuadros** [comment]
Closing as monarch-link-app has already been moved to unicorn!
