### ISSUE TITLE
Display progress when fetching from server

### ISSUE THREAD

**Issue by jeffbl** [Shared-Reality-Lab/IMAGE-browser#51]
Testing extension, and results are coming back in around 10s, nad I think longer on first run when starting with nothing running on GPU. There is no indication that the request was even received, and the window with results just pops up after the long wait. Hopefully we get faster as we optimize later, but even if it is a few seconds, some indication that the request was sent would be useful. If we can get any sort of legitimate progress, that would also be useful. Possibilities in order of niceness from least to most:

1. current behavior
2. Some spinning indicator / text that just tells user the request is sent
3. Progress indicator that says when different steps are done (e.g., "request sent", "image interpretation in progress", "creating experiences..."
4. Some sort of time remaining indicator along with previous

Assigning to UX team first for design.

**Comment by jeffbl** [comment]
As discussed, we don't currently have a way to know how long the server will take to return results, since it depends on the interpretation of the image, which preprocessors end up running, etc. Your 3 steps above could be implemented, but we'd have to get an estimate, and it'll require back and forth with the orchestrator. I think we should design that, but if that will take a while, based on user testing last week, should we immediately add something like a beep, or initial popup saying "IMAGE request sent" or something, so that the user at least immediately knows that they correctly triggered the functionality?

**Comment by Cybernide** [comment]
Noted - this is going to be next priority once other more pressing issues are resolved

**Comment by Sabrina-Knappe** [comment]
Yes, we need either an earcon or text that indicates that the image was sent. Otherwise it really does seem like nothing is happening.

**Comment by jeffbl** [comment]
For when you get to this again:
1. If earcon is needed, suggest roping in Florian
2. Given that results seem to take 5-10s now for when they come back, I suppose we could contemplate a fake progress bar if that would be helpful, just assuming that it'll take the max. time, and if it comes back sooner, hopefully user is pleasantly surprised. I hate fakery, though! Plus, if we performance optimize, we'd have to tweak that value over time, which may be an issue if it is coded into the extension. And, if user picks an alternative server, it might be faster or slower than our assumption. I think I've talked myself out of this being viable...

**Comment by Cybernide** [comment]
Well, there are ways of indicating that something is in progress without providing a definite "this is how much of it is done". For us sighted folks, it's like the hourglass indicator in classic Windows, or the spinning umbrella in MacOS. I'm assigning Florian to design. I suggest doing something similar to JAWS, which sounds a little like a clock ticking. Even though we might not be able to query how much longer we have, we can maybe do something like say quickly "Working". I.e.

3 seconds
Tick Tock sound
3 seconds
Tick Tock sound
3 seconds
"Working"
3 seconds
Tick Tock sound
3 seconds
Tick Tock sound
3 seconds
"Working"

**Comment by Cybernide** [comment]
Edited the comment above to reflect decisions from earlier this morning

**Comment by florian-grond** [comment]
instead of "request sent" we can put "IMAGE request sent"
The looping would be with reasonable intervals between repetitions say 2 seconds

**Comment by Cybernide** [comment]
Excellent - who do we assign for implementation?

**Comment by Cybernide** [comment]
[https://drive.google.com/file/d/13fU3NQ0tWjrgKSvmb9CuwkWUcsBrn2gv/view?usp=sharing](Processing data)
[https://drive.google.com/file/d/1z6WUiKcd6xjYIdamZBKsoevXzbTLuNeZ/view?usp=sharing](Results arrived)

**Comment by jeffbl** [comment]
@hongyec Is there remaining work on this? If not, please close.

**Comment by hongyec** [comment]
kk! closed!
