### ISSUE TITLE
How do we explain what each rendering type is, and how it works?

### ISSUE THREAD

**Issue by jeffbl** [Shared-Reality-Lab/IMAGE-browser#52]
Testing the extension, and am getting back multiple renderings, including

"An audio description of elements in the image with non-speech effects"
" An audio description of the elements in the image"

Each has sound effects, but I have no way of getting a description of what these indicate.

Suggestion: Each rendering should include a link to a pre-made description that explains how the rendering works, and maybe gives an example (audio, haptic, etc). Note that the description would need to be accessible as text for things like braille readers, as well as potentially pre-recorded audio.

Challenge 1: We could just include this in the blob that comes back from the server, but this would be extremely wasteful over time since the user might need the help a few times, but then will hopefully get the idea and not need it anymore. Hence the suggestion that it be a link that only downloads the content if needed.

Challenge 2: Accessing this should be obvious so that it is apparent to novice users, but not be a hassle in the long-run as another thing to have to navigate through each time one wants to access a rendering.

Assigning to UX for brainstorming / consideration / design first.

**Comment by Cybernide** [comment]
Seems like #126 has taken some of the scope of this issue.

**Comment by jeffbl** [comment]
#126 may help, but I suspect we're going to need something like this to really explain what all the tones, earcons, etc. mean for a particular rendering.

**Comment by Cybernide** [comment]
I'm thinking about writing up a supplementary set of in-depth documents explaining how to interpret all the renderings. Perhaps linked from the tutorial page, and accessible via a link on the renderings popup themselves.

**Comment by jeffbl** [comment]
I think the link from the renderings popup directly is likely to be much more fruitful, and also fits better with our extensible architecture, since we likely don't want to be responsible for updating the tutorial page every time anyone else changes the set of renderings on another server or something. Having a standard "Help link" for each handler makes more sense to me.

**Comment by jeffbl** [comment]
@Cybernide This is done, no? I assume we have to do more formal testing of it, but this was in for CSUN, correct? If so, please close, or else describe work still to be done. (Or create new, more specific work items for modifications post-CSUN)

**Comment by Cybernide** [comment]
Yes, this is finished. If anything comes up, I'll make a new issue.
