### ISSUE TITLE
Context menu should only display valid IMAGE server options

### ISSUE THREAD

**Issue by jeffbl** [Shared-Reality-Lab/IMAGE-browser#64]
As mentioned in #60, the maps context menu currently appears regardless of whether a map is currently selected. There is a general issue with the extension that IMAGE menu items should only appear (or be enabled) if currently on a supported object. Testing this in Brave (Chrome derivative), it appears that the standard is to simply remove irrelevant menu options. For example, if I right-click on a link, I don't get the "Save image as..." option at all, but it is present when I right-click on a picture.

Task is to create a general mechanism in the extension so that as new data types are added, we can identify them to know whether we should include the IMAGE menu item in a list, and make sure our existing data types work correctly.

@Cybernide My take is that we should have only a single IMAGE menu option that appears if the content is any of the types we deal with (currently graphics and Google embedded maps). Then, the extension decides what kind of query to make to the server (currently either graphic or maps lat/lng). I'm trying to think if there are cases where this is ambiguous in a meaningful way, such as if we would want both map and graphic renderings from a picture of a map. I don't recall how this code is currently structured, as "one or the other" or "can contain information for both".

**Comment by jeffbl** [comment]
@Cybernide Since this was logged, I don't think we still put the IMAGE option always on the context menu, so this may not be an issue anymore. Possibly requires a chat with @jaydeepsingh25 to discuss exactly how it works now and identify any holes, but if none found, this should be closed.

**Comment by Cybernide** [comment]
Testing it with Chrome, Edge and Vivaldi browsers seems to suggest that the context menu is showing up on the correct items.

**Comment by Cybernide** [comment]
@jaydeepsingh25 Can you quickly in the comments let us know the conditions under which the IMAGE context menu option appears? If it seems pretty bullet-proof, I'll close this issue.

**Comment by jeffbl** [comment]
No further issues found.
