### ISSUE TITLE
Remove haply options on browsers that do not support webserial

### ISSUE THREAD

**Issue by jeffbl** [Shared-Reality-Lab/IMAGE-browser#84]
Using the haply requires webserial, which is only supported in Chrome. If a check for webserial fails (as it will currently in firefox, since webserial is not supported) we should update the UI to remove any mentions of Haply, or give a message saying that Haply only works in Chrome (UI issue, so adding @Cybernide for that portion).

If we don't do this, users will be able to try to use it, and it will fail with an error at the first webserial call.

(Much of the above translated from conversation with @JRegimbal and @jaydeepsingh25 who may have more details when we need to tackle this.

**Comment by Cybernide** [comment]
@Clarisa1999 Can we do a simple browser check and disable haptic devices if its not on Chrome?

**Comment by Clarisa1999** [comment]
Thank you @Cybernide for the reference, it was helpful

**Comment by JRegimbal** [comment]
Just going to hop in and say the easiest check is for Web Serial support itself. On browsers that support it, `navigator.serial` returns the [entrypoint to the API](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/serial). Otherwise, it's `undefined`.

**Comment by Cybernide** [comment]
Ah, cool! Never mind, @Clarisa1999, go with @JRegimbal 's solution above.
