### ISSUE TITLE
Renderings popup window is often much too large

### ISSUE THREAD

**Issue by jeffbl** [Shared-Reality-Lab/IMAGE-browser#85]
Brave browser
Extension 0.1.0 from web store

On a large screen, when triggering the extension to get renderings, the window that pops up is the same size as the underlying browser window. Perhaps I'm unusual, but on a large screen at home, this means the window is enormous, and >80% whitespace. Can we size this down to come up over the underlying window at a more "reasonable" size given the content it contains? Assigning to @Cybernide for UI review, since I can imagine there might be reasons why we would want it to dominate the whole browser, e.g., for screen readers. But if not, please assign to @jaydeepsingh25 for implementation.

**Comment by jeffbl** [comment]
@Cybernide testing today on large machine, this is super irritating since it makes these enormous windows. I'm moving this into Aug08 milestone as a tweak, but if we can't get something smart done, would it at least be feasible to set a hard-coded maximum size?

**Comment by Cybernide** [comment]
I'm certain it wouldn't be a difficult fix to just set it to a maximum of the sum total of all the elements in the window

**Comment by jeffbl** [comment]
@jaydeepsingh25 I spoke with @Cybernide this morning, and she is ok with a hard-coded maximum size as a first take on this, and maybe that is good enough to call this done. If non-trivial to do even this, please ping here.
