### ISSUE TITLE
Test installing/using browser extension in Edge browser

### ISSUE THREAD

**Issue by jeffbl** [Shared-Reality-Lab/IMAGE-browser#97]
It appears that Microsoft Edge has a capability to install Chrome extensions directly from the Google Web store. We have one report that this didn't work for the IMAGE extension. This work item is to see if this actually works, and if not, what we need to do to deploy onto Edge.

**Comment by Cybernide** [comment]
So I've found some graphics that don't work, but here's the thing: they're the same ones that don't work in Chrome.

Doesn't actually send anything when you use it on the graphics in the news feed when you make a new tab, or when you go to the carousel graphics on the MSN news website.
![image](https://user-images.githubusercontent.com/7490996/154518836-12b5bced-4401-44cc-8251-12e61479a385.png)

To be fair, looking through the elements, I'd never be able to find the images in this page:
![image](https://user-images.githubusercontent.com/7490996/154519698-dd5af264-28ac-4b6c-995e-f0c950cba7b4.png)

Think it might be a similar case to the CBC website. Do we want to make this a separate issue? I'd say we reference my findings in another issue and close this one.

**Comment by jeffbl** [comment]
@cyan indicates she has tested and everything works as in Chrome, including settings. We need to make sure to test this again before major releases to make sure we don't break anything, but I'm closing this since it does currently work.
